### ISSUE TITLE
플레이어 Input Controller 동작 구현

### ISSUE THREAD

**Issue by pnudpwls1103** [pnudpwls1103/Scotophobia_Renew#1]
## Description
플레이어 움직임을 관할하는 스크립트 작성

## Todo

- [x] 플레이어 좌우 움직임
- [x] 전구 on/off
- [x] 마우스로 아이템 습득

## 참고 자료
- 플레이어 움직임 / 클릭 이벤트 (물체 클릭 했을 때 습득하는 코드)
이전 코드
[https://github.com/pnudpwls1103/Scotophobia/blob/117e8917784749c177ebb759dfae0cef6f5c8b63/Assets/Scripts/Player/PlayerController.cs](https://github.com/pnudpwls1103/Scotophobia/blob/117e8917784749c177ebb759dfae0cef6f5c8b63/Assets/Scripts/Player/PlayerController.cs)
- 전구 껐다키기
    - [https://github.com/pnudpwls1103/Scotophobia/tree/main/Assets/Scripts/Light](https://github.com/pnudpwls1103/Scotophobia/tree/main/Assets/Scripts/Light)
