### ISSUE TITLE
Player 모션 애니메이션 적용

### ISSUE THREAD

**Issue by pnudpwls1103** [pnudpwls1103/Scotophobia_Renew#10]
## Description
아트 Player 걷는 모션, 대기 모션 애니메이션 

## Todo
- [x] png -> sprite로 변경
- [x] animation 파일 생성 (아트 예시 사진 참고)
- [x] 스크립트에 애니메이션 변경 코드 적용

## 참고 자료
[Youtube 참고 영상](https://www.youtube.com/watch?v=IkvYstCzcoc)
