### ISSUE TITLE
스트레스바 UI

### ISSUE THREAD

**Issue by pnudpwls1103** [pnudpwls1103/Scotophobia_Renew#4]
## Description
스트레스바의 UI를 구현한다.

## Todo

- [ ] 스트레스 서서히 증가
- [ ] 스트레스 서서히 감소
- [ ] 주인공 데이터 - 스트레스 관리
