### ISSUE TITLE
정보창 UI

### ISSUE THREAD

**Issue by pnudpwls1103** [pnudpwls1103/Scotophobia_Renew#6]
## Description
아이템 습득 후 아이템에 대한 정보가 뜨는 UI를 구현한다.

## Todo

- [ ] 정보창의 내용을 마우스 클릭으로 넘기기
- [ ] 한 글자씩 뜨도록 구현
- [ ] 중복 클릭 방지 구현 
- [ ] 대사 관리
